### ISSUE TITLE
Formatting of Community Organisation

### ISSUE THREAD

**Issue by Abuk007** [cezar-berea/cnto-web#10]
http://carpenoctem.co/co

Formats nicely on 1366x768, but it has been reported that it falls apart on other resolutions.
Reference from Freghar: http://i.imgur.com/2xW5y09.png

Could this be fixed somehow so the formatting of page scales?

**Comment by supremefist** [comment]
I am too lazy to make this perfect for you, but I have limited the minimum size so it does not shrink to a size where it wraps!
