### ISSUE TITLE
Update "Live Chat" image

### ISSUE THREAD

**Issue by TRyujin** [cezar-berea/cnto-web#12]
We're switching from IRC to discord, so we'd need to have "IRC Live Chat" image replaces with following images.

https://drive.google.com/open?id=0B_J2O4Uo0Oh8bW1rNnhYY3hxX2M
https://drive.google.com/open?id=0B_J2O4Uo0Oh8X3BIQUlIREpFVHM
https://drive.google.com/open?id=0B_J2O4Uo0Oh8b3ZGNmp5SklRYW8

**Comment by supremefist** [comment]
I'll wait until the transition to discord is complete!

**Comment by supremefist** [comment]
Replaced the entire block with a slightly scaled version of the provided transparent asset. Removed the "join" text as I assume the "Discord" text in the asset is meant to replace it.
