### ISSUE TITLE
New version of qualifications tab

### ISSUE THREAD

**Issue by supremefist** [cezar-berea/cnto-web#15]
Members has a drop down menu I think we should do the same for qualifications.

The Main menu button should say Qualifications.

The drop down menu options should be Ribbons Overview and Ribbon Details.

We need to have qualificationv2 layout as the Ribbons Overview page but we several improvements for example the layout is fine but we need to be able to fit 6 ribbons in next to a members name so they need to be much closer together and preferably able to have lines of them so 6 ribbons on top and 6 below. The description of ribbons can be taken out completely.

The Ribbon Details page will be as per qualifications layout just need to update the quick buttons with new images.

**Comment by supremefist** [comment]
@CNTODachi I have added the basic implementations to
http://carpenoctem.co/ribbonsoverview and http://carpenoctem.co/ribbondetails

Please go over these two and comment here with the additional changes you need! I will add the dropdown on the main menu bar when we have finished polishing these!

I have done all the above mentioned stuff to the best of my ability, but still need the assets for the quick buttons on the ribbon details page.

**Comment by CNTODachi** [comment]
@Supremefist sorry it has been so long for the reply just getting back into things.

Ribbons overview tab looks great but can I ask what is the max in a row and are we able to have?

For the ribbon details page it looks like the font size for the description of each type of ribbon are different and the description needs to be center aligned if possible.

Also Ryujin and Abuk picked up the fact tge tables dont match up, any chance we can get them all lined up and the same?

**Comment by supremefist** [comment]
On it! Should be able to fit the 6 ribbons in a row, but I will ensure that
it breaks gracefully if there are more than that!

**Comment by CNTODachi** [comment]
Rgr thanks

**Comment by CNTODachi** [comment]
Here is the Red Storm Campaign ribbon for adding to the Ribbons available, also how is it coming along?

**Comment by supremefist** [comment]
Thanks! I will take care of this before the end of the week!

**Comment by supremefist** [comment]
@CNTODachi I have investigated the font sizes on the ribbon details page and they are identical... Could you confirm? I have also fixed most of the issues abovementioned. Can you confirm?

**Comment by CNTODachi** [comment]
Yes looks awesome mate, thank you very much.

**Comment by CNTODachi** [comment]
Hello Supreme here are the quick link icons also for implementation on the details page.

Training Ribbon Icon https://drive.google.com/open?id=0B3-_ejUb0TfTQWl3bFBESmx5NkE

Community Reward Ribbon Icon https://drive.google.com/open?id=0B3-_ejUb0TfTN0hRZGZjWjZWWm8

Qualification Ribbon Icon https://drive.google.com/open?id=0B3-_ejUb0TfTOUVhVFozdFlRV1k

Once that's done I think that is it just need to go over your PM on how to add to ribbons etc and should be good for deployment :)

**Comment by supremefist** [comment]
OK, I'm done!

I think we can worry about making it easy for you to add ribbons when the next new one comes! At the moment the code isn't well refactored for you to just add stuff. It will take more work to make it so.

**Comment by CNTODachi** [comment]
Yeah rgr nice work it looks awesome cheers.

**Comment by CNTODachi** [comment]
Shall we close this seems to be up and running now :)

**Comment by CNTODachi** [comment]
Closed as completed
