### ISSUE TITLE
Text alignment in lists

### ISSUE THREAD

**Issue by supremefist** [cezar-berea/cnto-web#8]
@HellfireLx: Sorry for my absence!  I have been quite busy with the CNTO django roster!  Freghar reported an issue and I was hoping you would be able to have a look at this:

Hey Supreme,
I've heard you have something to do with website administration for CNTO - if not, please ignore this. :)

Is there a chance you could fix (or find out what's wrong with) indenting of lists generated from bbcode (both "list" and "list=1")? When the item text is longer than a line and gets wrapped, the next line starts before the actual item mark (dot or number), making multi-line items very hard to read when surrounded by other paragraphs of text.

Demo:
single line item
another single line
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ullamcorper commodo purus ac porta. Ut ac aliquam velit. Morbi at pharetra arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas accumsan nisl non rutrum tincidunt. Fusce lacinia ipsum at enim maximus dignissim. Ut erat mauris, commodo sodales ex et, sollicitudin volutpat ante.
more items

Any chance this could be caused by custom CSS? (html <li> have a default padding of 40px unless overriden)

Thanks,
Fr

**Comment by supremefist** [comment]
Here is the demo with formatting!
![indent](https://cloud.githubusercontent.com/assets/2069824/11806727/c39f4c58-a31d-11e5-9680-c3dd13b13155.png)

**Comment by HellfireLx** [comment]
I can explain:

it's in enjin's bbcode.css

On the tag .bbcode_list { list-style:inside ; } , the inside argument has been put explicitly. It seems they use this trick, as without it, you can see the result in my screenshot below. I think the bullet list doesn't fit anymore in the overall post container. I thought we could override the behaviour, but the 'cheat' from enjin, seem to have its reasons.

![Alt Text](http://i.imgur.com/VbBjFQ5.png)

**Comment by supremefist** [comment]
Thanks a lot, Hellfire!
