### ISSUE TITLE
Updated Staff Needs box

### ISSUE THREAD

**Issue by supremefist** [cezar-berea/cnto-web#9]
Change Open to Enlist or Help or Apply button with hyperlink to Either PM of Branch Manager or new COC with separate branches with PM’s next to branch members names.

**Comment by supremefist** [comment]
@TRyujin @CNTODachi Handling of the links to PMs in the COC page is easy!  However, the way the COC page was built makes it difficult to directly activate a tab via URL.  I will have to investigate this further, but it is most certainly possible!

**Comment by TRyujin** [comment]
Sounds good. Let us know if you need anything.

**Comment by supremefist** [comment]
I did several things:
1. Staff needs box now has green "Apply" text next to each department that links to correct tab on CO page.
2. Each person on CO has a small envelope next to his name that links you directly into composing a PM.

**You still need to replace each user's URL in the CO html with the appropriate link.  All envelopes currently link to Ryujin!** 

Let me know if you have any issues!

**Comment by TRyujin** [comment]
This is exactly what we needed, great work Supreme. I'll get on adding appropriate links to each user.
